DROP DATABASE IF EXISTS tracker_db;

CREATE DATABASE tracker_db;

USE tracker_db;

CREATE TABLE department(
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(30)
);

CREATE TABLE role(
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(30),
salary DECIMAL NOT NULL,
department_id INTEGER NOT NULL
);

CREATE TABLE employee(
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
manager_id INTEGER NOT NULL
);